databases:
  - name: tweeterv1-db
    databaseName: tweeterv1
    user: tweeterv1

services:
  - type: web
    name: tweeterv1
    runtime: python
    buildCommand: ./build.sh
    startCommand: gunicorn tweeterapp.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: tweeterv1-db
          property: connectionString
